=== aminaousmane/ProjetXml/restaurant.dtd
<!ELEMENT restaurants (restaurant+)>
<!ELEMENT restaurant (coordonnees, carte, menus?)>
<!ELEMENT coordonnees (nom,adresse, nomRestaurateur, description, images*)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT nomRestaurateur (#PCDATA)>
<!ELEMENT description (#PCDATA|listes|paragraphes|textesImportants)*>
<!ELEMENT listes (#PCDATA)>
<!ELEMENT paragraphes (#PCDATA)>
<!ELEMENT textesImportants (#PCDATA)>
<!ELEMENT images EMPTY>
<!ATTLIST images position (gauche|droite|centre) #REQUIRED url CDATA #REQUIRED>
<!ELEMENT carte (plat+)>
<!ELEMENT plat (prix,descriptionPlat)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT descriptionPlat(#PCDATA|textesImportants)*>
<!ATTLIST plat id ID #REQUIRED nomPlat CDATA #REQUIRED partieRepas (entree|dessert|plat|fromage) #REQUIRED>
<!ATTLIST prix devise CDATA #REQUIRED>
<!ELEMENT menus (menu+)>
<!ELEMENT menu (descriptionMenu,prix,listePlats)>
<!ELEMENT descriptionMenu (#PCDATA)>
<!ELEMENT prix (#PCDATA)>
<!ELEMENT listePlats EMPTY>
<!ATTLIST menu titre CDATA #REQUIRED>
<!ATTLIST prix devise CDATA #REQUIRED>
<!ATTLIST listePlats idPlats IDREFS #REQUIRED>

=== aminaousmane/ProjetXml/restaurant.xml
<?xml version="1.0" encoding="utf8"?>
<?xml-stylesheet href="restaurant.xsl" type="text/css"?>
<!DOCTYPE cours SYSTEM "restaurant.dtd">
<restaurant>
	<coordonnees>

	</coordonnees>
	<carte>

	</carte>
</restaurant>
<restaurant>
	<coordonnees>
		<carte>

		</carte>
	</coordonnees>	
</restaurant>
<restaurant>
	<coordonnees>
		<carte>

		</carte>
	</coordonnees>	
</restaurant>
<restaurant>
	<coordonnees>
		<carte>

		</carte>
	</coordonnees>	
</restaurant>
